paths:
  static: public
  uploads: public/uploads
timezone: Asia/Taipei
markdown:
  engine: commonmark
  options:
    gfm: true
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
  source:
    path: ''
    icon: package_2
  notes:
    path: content/notes
    icon: notes
  posts:
    path: content/posts
    icon: event_available
  tags:
    path: content/tags
    icon: tabs
